sudo: required
dist: trusty
language: cpp
compiler: g++
cache: apt
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
addons:
  apt:
    packages:
    - gcc-4.7
    - g++-4.7
